# Difference between python and numpy

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3, 4, 5]
my_list * 6

[1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5]

In [3]:
my_numpy_arr = np.array(my_list)
my_numpy_arr * 6

array([ 6, 12, 18, 24, 30])

# Create Numpy array

## arange

In [4]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [5]:
np.arange(10, 23) - 10 + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [6]:
np.arange(10, 23).size

13

In [7]:
np.arange(10, 26, 5)

array([10, 15, 20, 25])

In [8]:
np.arange(26, step=5)

array([ 0,  5, 10, 15, 20, 25])

## linspace

In [9]:
np.linspace(5, 7, 9)

array([ 5.  ,  5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ])

In [10]:
np.linspace(5, 7, 9, retstep=True)

(array([ 5.  ,  5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ]), 0.25)

## zeros

In [11]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [12]:
np.zeros((5, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [13]:
np.zeros(11, dtype="int64")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## ones

In [14]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [15]:
np.ones((5,4,3))

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

# Index, slice, iterate

## Single element